---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kozepen/public_html/docgptio.com/client
    - /bin/cp -r $DEPLOYPATH/client $DEPLOYPATH/docgptio.com/client
    - /bin/cp -r $DEPLOYPATH/.next $DEPLOYPATH/docgptio.com/client
