# ----- PINECONE CONFIG -----
PINECONE_API_KEY: "9a1ef3ab-6ec6-4e8b-a7ed-480a6cd21c38"
PINECONE_INDEX: "docgpt" 
PINECONE_ENV: "northamerica-northeast1-gcp"

# ----- SERVER PORT ----
SERVER_PORT: "8000"

# ---- OPENAI CONFIG -----
EMBEDDINGS_MODEL: "text-embedding-ada-002"
GENERATIVE_MODEL: "gpt-3.5-turbo" # use gpt-4 for better results
EMBEDDING_DIMENSIONS: 1536
TEXT_EMBEDDING_CHUNK_SIZE: 200
COSINE_SIM_THRESHOLD: 0.7
MAX_TEXTS_TO_EMBED_BATCH_SIZE: 100
MAX_PINECONE_VECTORS_TO_UPSERT_PATCH_SIZE: 100
